#!/bin/bash
#PBS -l nodes=1:ppn=12,vmem=120gb,walltime=1:00:00
#PBS -N pRF
#PBS -V

set -e
set -x

fmri=$(jq -r .fmri[] config.json)
stim=$(jq -r .stim[] config.json)
fsdir=$(jq -r .output config.json)
preprocess=$(jq -r .preprocess config.json)
export TR=$(jq -r .TR config.json)

# do preprocessing if "preprocessing" tag not present
./preprocess.sh

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

if [ ! -f $(jq -r .mask config.json) ]; then
  echo "creating mask"
  time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./create_mask.sh $fsdir
fi

mkdir -p prf
[ -f ~/.mrDefaults.mat ] && rm -rf ~/.mrDefaults.mat # remove .mrDefaults.mat in home directory

echo "running pRF"
time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
if [ ! -s ./prf/r2.nii.gz ];
then
	echo "output missing"
	exit 1
fi

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./create_vtks.sh $fsdir
